SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
case when STATUS = 'SALE' THEN '판매중' when STATUS = 'RESERVED' THEN '예약중' 
when STATUS = 'DONE' THEN '거래완료' END AS STATUS
FROM USED_GOODS_BOARD
where CREATED_DATE = '2022-10-05'
order by BOARD_ID DESC