-- 코드를 입력하세요
SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK AS a
INNER JOIN AUTHOR AS b
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE a.CATEGORY = "경제"
ORDER BY PUBLISHED_DATE;